//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionValesRdz
{
    using System;
    using System.Collections.Generic;
    
    public partial class logs
    {
        public int id { get; set; }
        public int id_usuario { get; set; }
        public string direccion_ip { get; set; }
        public string host { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
