//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionValesRdz
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ValesRdzDatosEntities : DbContext
    {
        public ValesRdzDatosEntities()
            : base("name=ValesRdzDatosEntities")
        {
        }

        // --- AÑADE ESTE NUEVO CONSTRUCTOR ---
        public ValesRdzDatosEntities(string connectionString, bool nueva)
            : base(connectionString)
        {
        }
        // --- FIN DEL CÓDIGO A AÑADIR ---

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<empresas> empresas { get; set; }
        public virtual DbSet<logs> logs { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<vales> vales { get; set; }
        public virtual DbSet<ventas> ventas { get; set; }
        public virtual DbSet<estaciones> estaciones { get; set; }
        public virtual DbSet<permisos> permisos { get; set; }
    }
}
