//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionValesRdz
{
    using System;
    using System.Collections.Generic;
    
    public partial class vales
    {
        public int id { get; set; }
        public int folio { get; set; }
        public string estatus { get; set; }
        public System.DateTime fecha_emision { get; set; }
        public Nullable<System.DateTime> fecha_canje { get; set; }
        public double importe { get; set; }
        public string importe_letra { get; set; }
        public int id_cliente { get; set; }
        public int id_empresa { get; set; }
        public int id_usuario { get; set; }
        public string token { get; set; }
        public Nullable<int> id_estacion { get; set; }
        public Nullable<System.DateTime> fecha_corte { get; set; }
        public string codigo { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual empresas empresas { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual estaciones estaciones { get; set; }
    }
}
