//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionValesRdz
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas
    {
        public int id { get; set; }
        public int folioInicio { get; set; }
        public int folioFin { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public double denominacion { get; set; }
        public int cantidad { get; set; }
        public Nullable<double> importe { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual empresas empresas { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
